twitter:
  consumer_key: 'NdgZeu4tT2MDIFQzd8v2WHQ62'
  consumer_secret: 'eFvcz52ecK4zsrDgQDz5QFTE0f2Xxh0S9ThSyh5NLPE79cnojd'
  oauth_token: '31439619-5SBfSSz03mAHpkWTyAE8KxMbs3kGJzB73IlDO3PPS'
  oauth_token_secret: 'VQo28ZarlURy8VBO04vQBmcil94oBJwcjQFMcWuHwyZME'
